"""
This is a setup.py script generated by py2applet

Usage:
    python3 setup.py py2app
"""

from setuptools import setup

with open("README.md", 'r') as f:
    long_description = f.read()

setup(
    name='pyet',
    version='1.0',
    author='Daniel Palma',
    license="MIT",
    long_description=long_description,
    author_email='danivgy@gmail.com',
    scripts=['pyet/pyet.py'],
    description='Minimal lyrics for your spotify songs.',
    install_requires=['pyobjc', 'bs4']
)
