"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['pyet/pyet.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'pyet_icon.icns',
    'plist': {
        'CFBundleName': 'pyet',
        'CFBundleShortVersionString': '1.0.0',
        'CFBundleVersion': '1.0.0'
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    name='pyet',
    version='1.0',
    author='Daniel Palma',
    license="MIT",
    author_email='danivgy@gmail.com',
    url='https://github.com/danthelion/pyet',
    scripts=['pyet/pyet.py'],
    description='Minimal lyrics display for your Spotify tracks.',
    install_requires=['pyobjc', 'bs4']
)
